### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Luz1727#1]
[Infografia-LuzArlethLB.pdf](https://github.com/user-attachments/files/16753132/Infografia-LuzArlethLB.pdf)

**Comment by AmilkarVladimiR** [comment]
20% Excelente 👍

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
